id: P001719
initial_creation_type: ocr
source_metadata:
  id: bdr:W2CZ7936
  title: གྲགས་པ་རྒྱལ་མཚན་གྱི་རྣམ་ཐར་རྣལ་ལམ་མ་
  author: ''
  volumes:
    fa5e3ff96a29447a872e55278d01169f:
      image_group_id: I1KG3442
      title: ''
      volume_number: 1
      total_pages: 16
      base_file: v001.txt
