id: I59613189
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T11:05:10+00:00'
last_modified: '2022-06-07T14:11:51.411682+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2CZ7936
  title: གྲགས་པ་རྒྱལ་མཚན་གྱི་རྣམ་ཐར་རྣལ་ལམ་མ་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C48C:
      image_group_id: I1KG3442
      title: ''
      total_pages: 16
      order: 1
      base_file: C48C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
